### ISSUE TITLE
GVL Property Name Mismatch

### ISSUE THREAD

**Issue by shortaflip** [chrispaterson/iabtcf-es#19]
### Issue
The private function mapVendors() uses purposeIds, featureIds, and etc. starting from line 403 in GVL.ts, creating a mismatch with version 2 of the global vendor list found here: [consensu vendor list](https://vendorlist.consensu.org/v2/vendor-list.json).

### Fix
Change name to match GVL.
Example: purposeIds -> purposes

**Comment by chrispaterson** [comment]
Fixed by #21
